@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMxNDE3Nzh9.u3nXy1r-YulssfLV7_nol61BmPJkmn4UGRlCMMVniPg

###Products index
GET http://localhost:3000/products?price=3
Authorization: Bearer {{ jwt }}

###Products show  
GET http://localhost:3000/products/4
Authorization: Bearer {{ jwt }}


###Products create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "lettuce",
  "price": "1",
  "image_url": null,
  "description": "healthy!",
  "inventory": 200
}

### Products update
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "description": "with garlic!"
}
### Products Destroy
DELETE http://localhost:3000/products/8



### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Romeo",
  "email": "romeo@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "bagel@gmail.com",
  "password": "password"
}

###Orders index

GET http://localhost:3000/orders/

###Orders show

GET http://localhost:3000/orders/2
Authorization: Bearer {{ jwt }}

###Orders create

POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 2,
  "quantity": 5,
}